# # docker-compose.yml 

version: "3.8"

services:
  censuscope:
    image: ghcr.io/gw-hive/censuscope:2.1.0
    container_name: censuscope_localtest
    command: >
      python lib/censuscope.py
      -i 5
      -s 10
      -t family
      -q /app/data/[query.fastq]
      -d /app/data/[path/to/blast_db]
    volumes:
      - [/your/data]:/app/data
      - ./temp_dirs:/app/temp_dirs

    stdin_open: true
    tty: true
